export * from './home'
export * from './privacy-policy'
export * from './open-account'
export * from './corruption-policy'
export * from './kyc-policy'
export * from './ethics-code'
export * from './social-responsibility-program'